mode: deployment
image:
  repository: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector
  tag: 0.45.0
livenessProbe:
  httpGet:
    path: /
    port: 13133
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2

readinessProbe:
  httpGet:
    path: /
    port: 13133
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
command:
  name: dynatrace-otel-collector
extraEnvs:
- name: DT_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_API_TOKEN
- name: DT_ENDPOINT
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_ENDPOINT
resources:
  limits:
    memory: 450Mi
config:
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
          cors:
            allowed_origins:
              - "http://*"
              - "https://*"
    filelog: null

  processors:
    cumulativetodelta: {}

  exporters:
    debug:
      verbosity: detailed
    otlp_http:
      endpoint: "${env:DT_ENDPOINT}"
      headers:
        Authorization: "Api-Token ${env:DT_API_TOKEN}"

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: []
        exporters: [otlp_http]
      metrics:
        receivers: [otlp]
        processors: [cumulativetodelta]
        exporters: [otlp_http]
      logs:
        receivers: [otlp]
        processors: []
        exporters: [otlp_http]