# Ref: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/values.yaml
opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false
prometheus:
  enabled: false
components:
  accounting:
    enabled: false
  ad:
    enabled: false
  cart:
    enabled: true
  checkout:
    enabled: true
  currency:
    enabled: true
  email:
    enabled: false
  # cart:
  #   enabled: true
  #   initContainers:
  #     - name: wait-for-valkey-cart
  #       image: busybox:1.28
  #       command: ['sh', '-c', 'until nc -z -v -w30 valkey-cart 6379; do sleep 2; done']
  flagd:
    # Turn off flagd-ui as it always crashes and we don't need it
    sidecarContainers: []
  fraud-detection:
    enabled: false
  frontend:
    enabled: true
  frontend-proxy:
    enabled: true
  image-provider:
    enabled: true
  load-generator:
    enabled: true
    resources:
      limits:
        memory: 500Mi
  payment:
    enabled: true
  product-catalog:
    resources:
      limits:
        memory: 200Mi
  product-reviews:
    enabled: false
  quote:
    enabled: true
  recommendation:
    enabled: false
  shipping:
    enabled: true
  kafka:
    enabled: true
  postgresql:
    enabled: true
  product-reviews:
    enabled: false
  llm:
    enabled: false
  valkey-cart:
    enabled: true

default:
  image:
    repository: ghcr.io/open-telemetry/demo
    tag: "2.2.0"
  env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.labels['app.kubernetes.io/component']"
    - name: OTEL_COLLECTOR_NAME
      value: 'dynatrace-collector-opentelemetry-collector'
